### PR TITLE
Add Training Data #35 - added images of uranus

### PR DESCRIPTION
**Pull request by SambhaviPD**
@ritwik12 - Added few images of uranus in training folder. Are these okay or you looking for satellite type ones?

### CODE REVIEW

**Comment by ritwik12** [comment]
@SambhaviPD Thanks, these are good. Few images have issues.

```
031 is having text, better to remove that to not confuse the model while training.
033 and 036 have earth too in image, lets remove both images.
037 is Neptune not Uranus if I am correct
```

Please remove these and renumber images.

**Comment by SambhaviPD** [comment]
@ritwik12 - Incorporated your suggestions and added some more. If these are okay, I can add more, not just uranus, other planets too.

**Comment by ritwik12** [comment]
@SambhaviPD Thanks!!

**Comment by ritwik12** [comment]
@SambhaviPD Sure, you can add. But I assume you are doing this for learning. I would suggest you developed some script which you can use to find data from the internet. That way you would learn data collection. Manually doing it will do no good to you and I don't want you to waste your precious time doing that.

If not that you can contribute in some other way too in this project, Add something, improve. If you need help you can get that too here.

**Comment by SambhaviPD** [comment]
@ritwik12 - Yes, I use a piece of python code where I use bing search API to grab images. I just manually scan good ones from the grabbed bunch and then commit them to git. I learn Deep Learning for work (it's an ocean, so learning will never stop), so am quite well versed with the process of Data collection, annotation, and those. Sure, I shall take a deeper look at the repo entirely and suggest my thoughts on improvement and any ideas that I may have. Thanks for your kind words!

**Comment by ritwik12** [comment]
@SambhaviPD :)

**Pull request merged**
