### PR TITLE
Created a new branch from master, applied renaming script to test_data

### PR DESCRIPTION
**Pull request by attard-andrew**
@ritwik12 - Here's what I did:

- Cancelled the inital pull request
- Deleted my previously created branch
- Switched to the master
- Created a NEW branch from the master
- Completed my changes to the test_data using the script previously created
- Pushed & submit this pull request

### CODE REVIEW

**Comment by ritwik12** [comment]
@attard-andrew You forgot to run the script I guess

**Comment by attard-andrew** [comment]
So I definitely ran it - what happened was that I did my git add from the incorrect working directory - so the files were untracked. New push incoming..

**Comment by ritwik12** [comment]
@Your PR contains some clutter like you have removed a few files from training data as well.
Also, please create directories for each type in testing data so that we will be aware of that.

Change path from `samples/image_retraining/test_data/001.jpg` to `amples/image_retraining/test_data/earth/001.jpg`

**Comment by attard-andrew** [comment]
@ritwik12 - sorry for the slow follow up, I've been traveling the last few days.  When you mention the clutter similar to training data:
- After creating a new branch from the master to use for modifying the test_data files, I did not modify the training_data folder either through the GUI or other means. However, when comparing it to the original I CAN indeed see a discrepancy of about 3Mb.  Is there anything in my script that you can see might cause this?  Since this has happened more than once, I'm really confused about what could have caused it

In any case - I've restored the original folder from your repo.  For the test_data, I manually created subdirectories & sorted the images (I figured manually was the only option in this case outside of utilizing the tool you're building once complete).  Once the images were in their respective directories, I re-ran the tool to rename them accordingly

**Comment by ritwik12** [comment]
@attard-andrew Sorry I missed this. I guess you might have started the training of the model somehow by using commands mentioned on README.md. So everytime you will start training it's going to cause the files to be changed.

Also, you have added `.vscode/` by mistake. It is better to take care when you are using git add command. I will add it and remove myself for now. and will add in gitignore also.

**Pull request merged**
