### PR TITLE
[Deploy on heroku] Procfile added

### PR DESCRIPTION
**Pull request by priyalekande**
To deploy the webpages on heroke

### CODE REVIEW

**Comment by priyalekande** [comment]
Procfile has been added to the code which will help Horeku to deploy the webapp

**Comment by priyalekande** [comment]
further steps will be 

- [ ] Create a horeku account
- [ ] Create new app
- [ ] Connect your GitHub account to Heroku
- [ ] Deploy the app

**Comment by ritwik12** [comment]
Thanks @priyalekande. I will check the steps further and will update here.

**Comment by priyalekande** [comment]
Sure @ritwik12

**Comment by ritwik12** [comment]
Thanks @priyalekande. I have deployed the app at https://celestial-bodies-detection.herokuapp.com/ with the help of this PR.

**Pull request merged**
