### PR TITLE
added uranus training images

### PR DESCRIPTION
**Pull request by kannandreams**
I have added few uranus training images to improve classifier training performance.

### CODE REVIEW

**Comment by kannandreams** [comment]
Please review and also happy to contribute more .

**Comment by ritwik12** [comment]
@kannandreams Thanks for the PR :) , Please remove `/uranus_cv_modified.png` and `/uranus_6.png` as they seem inappropriate.

**Comment by kannandreams** [comment]
Thanks for quick response and review. Removed the files as requested.

**Comment by ritwik12** [comment]
@kannandreams Thanks !!

**Comment by kannandreams** [comment]
Thanks for merging. Looking forward to contributing more.

**Pull request merged**
